name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        run: |
          go install gotest.tools/gotestsum@latest
          go install github.com/go-task/task/v3/cmd/task@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest

      - name: Check
        run: |
          task format
          task shadow

      - name: Build
        run: task build

      - name: Unit tests
        run: task test
